<?php

namespace ContainerGjtfJ5W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedLearningPathEtapesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SeedLearningPathEtapesCommand' shared autowired service.
     *
     * @return \App\Command\SeedLearningPathEtapesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SeedLearningPathEtapesCommand.php';

        $container->privates['App\\Command\\SeedLearningPathEtapesCommand'] = $instance = new \App\Command\SeedLearningPathEtapesCommand(($container->privates['App\\Repository\\LearningPathRepository'] ?? $container->load('getLearningPathRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:seed-learning-path-etapes');
        $instance->setDescription('Ajoute des étapes exemples aux parcours sans étapes');

        return $instance;
    }
}
