<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Skill extends \App\Entity\Skill implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null, 16],
        "\0".parent::class."\0".'contexte_skill' => [parent::class, 'contexte_skill', null, 16],
        "\0".parent::class."\0".'createur' => [parent::class, 'createur', null, 16],
        "\0".parent::class."\0".'description_skill' => [parent::class, 'description_skill', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'learningPaths' => [parent::class, 'learningPaths', null, 16],
        "\0".parent::class."\0".'nom_skill' => [parent::class, 'nom_skill', null, 16],
        'categorie' => [parent::class, 'categorie', null, 16],
        'contexte_skill' => [parent::class, 'contexte_skill', null, 16],
        'createur' => [parent::class, 'createur', null, 16],
        'description_skill' => [parent::class, 'description_skill', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'learningPaths' => [parent::class, 'learningPaths', null, 16],
        'nom_skill' => [parent::class, 'nom_skill', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
