<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'EMAIL' => [parent::class, 'EMAIL', null, 16],
        "\0".parent::class."\0".'IMAGE' => [parent::class, 'IMAGE', null, 16],
        "\0".parent::class."\0".'NOM' => [parent::class, 'NOM', null, 16],
        "\0".parent::class."\0".'NUMERO' => [parent::class, 'NUMERO', null, 16],
        "\0".parent::class."\0".'PRENOM' => [parent::class, 'PRENOM', null, 16],
        "\0".parent::class."\0".'ROLE' => [parent::class, 'ROLE', null, 16],
        "\0".parent::class."\0".'articles' => [parent::class, 'articles', null, 16],
        "\0".parent::class."\0".'commentaires' => [parent::class, 'commentaires', null, 16],
        "\0".parent::class."\0".'condidatureJobs' => [parent::class, 'condidatureJobs', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'offrejobs' => [parent::class, 'offrejobs', null, 16],
        "\0".parent::class."\0".'publications' => [parent::class, 'publications', null, 16],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null, 16],
        "\0".parent::class."\0".'skills' => [parent::class, 'skills', null, 16],
        'EMAIL' => [parent::class, 'EMAIL', null, 16],
        'IMAGE' => [parent::class, 'IMAGE', null, 16],
        'NOM' => [parent::class, 'NOM', null, 16],
        'NUMERO' => [parent::class, 'NUMERO', null, 16],
        'PRENOM' => [parent::class, 'PRENOM', null, 16],
        'ROLE' => [parent::class, 'ROLE', null, 16],
        'articles' => [parent::class, 'articles', null, 16],
        'commentaires' => [parent::class, 'commentaires', null, 16],
        'condidatureJobs' => [parent::class, 'condidatureJobs', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'offrejobs' => [parent::class, 'offrejobs', null, 16],
        'publications' => [parent::class, 'publications', null, 16],
        'reservations' => [parent::class, 'reservations', null, 16],
        'skills' => [parent::class, 'skills', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
