<?php

namespace ContainerZBZ4r7V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R3k4mS8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r3k4mS8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Front\\MarketplaceController::ajouter' => ['privates', '.service_locator.0Jg4tST', 'get_ServiceLocator_0Jg4tSTService', true],
            'App\\Controller\\Front\\MarketplaceController::ajouterCategorie' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Front\\MarketplaceController::ajouterPublic' => ['privates', '.service_locator.1Jm4ZFN', 'get_ServiceLocator_1Jm4ZFNService', true],
            'App\\Controller\\Front\\MarketplaceController::categories' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\Front\\MarketplaceController::detail' => ['privates', '.service_locator.b12wXHr', 'get_ServiceLocator_B12wXHrService', true],
            'App\\Controller\\Front\\MarketplaceController::index' => ['privates', '.service_locator.WcjdkrB', 'get_ServiceLocator_WcjdkrBService', true],
            'App\\Controller\\Front\\MarketplaceController::mesArticles' => ['privates', '.service_locator.b12wXHr', 'get_ServiceLocator_B12wXHrService', true],
            'App\\Controller\\Front\\MarketplaceController::modifier' => ['privates', '.service_locator.CPsey38', 'get_ServiceLocator_CPsey38Service', true],
            'App\\Controller\\Front\\MarketplaceController::modifierCategorie' => ['privates', '.service_locator.0Jg4tST', 'get_ServiceLocator_0Jg4tSTService', true],
            'App\\Controller\\Front\\MarketplaceController::supprimer' => ['privates', '.service_locator.6xBERtV', 'get_ServiceLocator_6xBERtVService', true],
            'App\\Controller\\Front\\MarketplaceController::supprimerCategorie' => ['privates', '.service_locator.0Jg4tST', 'get_ServiceLocator_0Jg4tSTService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Front\\MarketplaceController:ajouter' => ['privates', '.service_locator.0Jg4tST', 'get_ServiceLocator_0Jg4tSTService', true],
            'App\\Controller\\Front\\MarketplaceController:ajouterCategorie' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Front\\MarketplaceController:ajouterPublic' => ['privates', '.service_locator.1Jm4ZFN', 'get_ServiceLocator_1Jm4ZFNService', true],
            'App\\Controller\\Front\\MarketplaceController:categories' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\Front\\MarketplaceController:detail' => ['privates', '.service_locator.b12wXHr', 'get_ServiceLocator_B12wXHrService', true],
            'App\\Controller\\Front\\MarketplaceController:index' => ['privates', '.service_locator.WcjdkrB', 'get_ServiceLocator_WcjdkrBService', true],
            'App\\Controller\\Front\\MarketplaceController:mesArticles' => ['privates', '.service_locator.b12wXHr', 'get_ServiceLocator_B12wXHrService', true],
            'App\\Controller\\Front\\MarketplaceController:modifier' => ['privates', '.service_locator.CPsey38', 'get_ServiceLocator_CPsey38Service', true],
            'App\\Controller\\Front\\MarketplaceController:modifierCategorie' => ['privates', '.service_locator.0Jg4tST', 'get_ServiceLocator_0Jg4tSTService', true],
            'App\\Controller\\Front\\MarketplaceController:supprimer' => ['privates', '.service_locator.6xBERtV', 'get_ServiceLocator_6xBERtVService', true],
            'App\\Controller\\Front\\MarketplaceController:supprimerCategorie' => ['privates', '.service_locator.0Jg4tST', 'get_ServiceLocator_0Jg4tSTService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Front\\MarketplaceController::ajouter' => '?',
            'App\\Controller\\Front\\MarketplaceController::ajouterCategorie' => '?',
            'App\\Controller\\Front\\MarketplaceController::ajouterPublic' => '?',
            'App\\Controller\\Front\\MarketplaceController::categories' => '?',
            'App\\Controller\\Front\\MarketplaceController::detail' => '?',
            'App\\Controller\\Front\\MarketplaceController::index' => '?',
            'App\\Controller\\Front\\MarketplaceController::mesArticles' => '?',
            'App\\Controller\\Front\\MarketplaceController::modifier' => '?',
            'App\\Controller\\Front\\MarketplaceController::modifierCategorie' => '?',
            'App\\Controller\\Front\\MarketplaceController::supprimer' => '?',
            'App\\Controller\\Front\\MarketplaceController::supprimerCategorie' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Front\\MarketplaceController:ajouter' => '?',
            'App\\Controller\\Front\\MarketplaceController:ajouterCategorie' => '?',
            'App\\Controller\\Front\\MarketplaceController:ajouterPublic' => '?',
            'App\\Controller\\Front\\MarketplaceController:categories' => '?',
            'App\\Controller\\Front\\MarketplaceController:detail' => '?',
            'App\\Controller\\Front\\MarketplaceController:index' => '?',
            'App\\Controller\\Front\\MarketplaceController:mesArticles' => '?',
            'App\\Controller\\Front\\MarketplaceController:modifier' => '?',
            'App\\Controller\\Front\\MarketplaceController:modifierCategorie' => '?',
            'App\\Controller\\Front\\MarketplaceController:supprimer' => '?',
            'App\\Controller\\Front\\MarketplaceController:supprimerCategorie' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.r3k4mS8'])) {
            return $container->privates['.service_locator.r3k4mS8'];
        }

        return $container->privates['.service_locator.r3k4mS8'] = $instance;
    }
}
