<?php

namespace ContainerZBZ4r7V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CPsey38Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CPsey38' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.CPsey38'])) {
            return $container->privates['.service_locator.CPsey38'];
        }

        return $container->privates['.service_locator.CPsey38'] = $instance;
    }
}
