<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP6h9xFR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP6h9xFR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP6h9xFR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP6h9xFR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP6h9xFR\App_KernelDevDebugContainer([
    'container.build_hash' => 'P6h9xFR',
    'container.build_id' => '2896c0c8',
    'container.build_time' => 1770576187,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP6h9xFR');
