<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKeQ7mlo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKeQ7mlo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKeQ7mlo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKeQ7mlo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKeQ7mlo\App_KernelDevDebugContainer([
    'container.build_hash' => 'KeQ7mlo',
    'container.build_id' => '52146dcb',
    'container.build_time' => 1770571782,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKeQ7mlo');
