<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ6gLThZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ6gLThZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ6gLThZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ6gLThZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ6gLThZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z6gLThZ',
    'container.build_id' => '0da0e053',
    'container.build_time' => 1770671283,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ6gLThZ');
